### ISSUE TITLE
Operator.yaml referencing non-existent secret

### ISSUE THREAD

**Issue by pbstriker38** [3scale/aws-nlb-helper-operator#10]
The  `/deploy/iam-service-account/operator.yaml` is referencing the `AWS_REGION` secret. This secret is only created if using the IAM env credentials deployment. This can be changed to read from a configmap or just a hard coded value in the deployment.

**Comment by raelga** [comment]
Thanks @pbstriker38, we will update the documentation asap and add some static check to avoid the issue in the future.
