### ISSUE TITLE
Change operator scope from namespace to cluster

### ISSUE THREAD

**Issue by slopezz** [3scale/aws-nlb-helper-operator#5]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Being a networking operator, where you might be interested in fine tuning NLBs on different Namespaces, it would be nice not having to the deploy the operator on every Namespace where you have Services to modify, so just deploy it once with cluster scope, and being able to watch Services on any (or on specific) Namespace/s.

**Describe alternatives you've considered**
N/A

**Additional context**
Bear in mind, on some restricted scenarios like OSD, there should be some specific restrictions on cluster scope operators, so it would be nice to take it into account before implementing a solution.

**Comment by mxmmarmol** [comment]
Agree, I am currently working to different ingress controllers in different namespaces, I need to replicate this operator in order to properly work.

**Comment by raelga** [comment]
Closed by #18. The operator now supports all, single and multi-namespace operation.
