### ISSUE TITLE
feat: Add support for IAM role service account authentication

### ISSUE THREAD

**Issue by haghabozorgi** [3scale/aws-nlb-helper-operator#6]
**Is your feature request related to a problem? Please describe.**
Currently it seems the operator only supports iam user credentials, It would be very helpful if the operator would support IAM roles for service accounts. We are attempting to use nginx-ingress with 'nlb' LB type via helm chart, and we would like to set the proxy_protocol_v2 attribute for a subset of the LBs. The operator would help us solve this problem but we would like to avoid creating an iam user.

**Describe the solution you'd like**
Perhaps the operator could add config flags for which cred type is being used, or some type of ordering(attempt iam role, fallback to aws credentials file/vars, etc).

**Describe alternatives you've considered**
We may just use a null_resource in tf for the time being to set it, but it is certainly not as tidy.

**Comment by raelga** [comment]
Welcome @haghabozorgi, thank you very much for the proposal!

Let me look into it and get back to you.

**Comment by raelga** [comment]
Hello @haghabozorgi!

The support for IAM Roles for service accounts has been implemented in #8. It will be merged next week once the PR is reviewed.

**Comment by raelga** [comment]
This feature has been implemented in #8, thanks to @haghabozorgi for the suggestion!

**Comment by haghabozorgi** [comment]
@raelga thanks for your efforts on this.
